version: '3.8'

networks:
  backend:
    name: backend
    driver: bridge  
  frontend:
    name: frontend
    driver: bridge

volumes:
  postgres_data:
    name: postgres_data
  static_volume:
    name: static_volume
  media_volume:  
    name: media_volume

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./web:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - ./.env/.env.dev
    networks:
      - frontend
      - backend
#    command: tail -f /dev/null
    command: python manage.py runserver
    
  db:
    image: postgres:14.0-alpine
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env/.env.dev.db
    networks:
      - backend

  redis:
    image: "redis:alpine"
    container_name: cache
    ports:
      - "6379:6379"
    networks:
      - backend

