# Generated by Django 5.0.4 on 2024-04-24 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accompte', '0002_alter_accountpage_tooltip_alter_emailpage_tooltip_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CGSUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Clair'), ('dark', 'Sombre'), ('system', 'Système')], default='clair', max_length=10)),
                ('icons', models.CharField(choices=[('fonce', 'Vert émeraude'), ('clair', 'Vert pomme'), ('cyan', 'Cyan'), ('gris', 'Gris')], default='cyan', max_length=10)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cgs_userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
