# Traduction
from django.utils.translation import gettext_lazy as _

# OPTIONS DE TABLES
TABLE_OPTIONS = {
    'minSpareRows': 0,
    'startRows': 3,
    'startCols': 3,
    'colHeaders': True,
    'rowHeaders': True,
    'contextMenu': [
        'row_above', 
        'row_below', 
        '---------',
        'col_left', 
        'col_right', 
        '---------',
        'remove_row', 
        'remove_col', 
        '---------',
        'undo', 
        'redo', 
        '---------',
        'copy', 
        'cut', 
        '---------',
        'alignment',
        '---------',
        'mergeCells',
    ],
    'height': 108,
    'language': 'fr-FR',
    'renderer': 'text',
    'autoColumnSize': False,
    'mergeCells': True,
}

# Itération des bg_colors
ITER_COLORS = [
    "on_red", 
    "on_green", 
    "on_yellow", 
    "on_blue", 
    "on_magenta", 
    "on_cyan", 
    "on_white"
]
 
# traduction de la position d'un entier en littéral
POSITIONS_TRANSLATIONS = {
    'M': {
        1: "au premier",
        2: "au deuxième",
        3: "au troisième",
        4: "au quatrième",
        5: "au cinquième",
        6: "au sixième",
        7: "au septième",
        8: "au huitième",
        9: "au neuvième",
        10: "au dixième",
        11: "au onzième",
        12: "au douzième",
        13: "au treizième",
        14: "au quatorzième",
        15: "au quinzième",
        16: "au seizième",
        17: "au dix-septième",
        18: "au dix-huitième",
        19: "au dix-neuvième",
        20: "au vingtième",
        21: "au vingt-et-unième",
        22: "au vingt-deuxième",
        23: "au vingt-troisième",
        24: "au vingt-quatrième",
        25: "au vingt-cinquième",
        26: "au vingt-sixième",
        27: "au vingt-septième",
        28: "au vingt-huitième",
        29: "au vingt-neuvième",
        30: "au trentième",
    },
    'F': {
        1: "à la première",
        2: "à la deuxième",
        3: "à la troisième",
        4: "à la quatrième",
        5: "à la cinquième",
        6: "à la sixième",
        7: "à la septième",
        8: "à la huitième",
        9: "à la neuvième",
        10: "à la dixième",
        11: "à la onzième",
        12: "à la douzième",
        13: "à la treizième",
        14: "à la quatorzième",
        15: "à la quinzième",
        16: "à la seizième",
        17: "à la dix-septième",
        18: "à la dix-huitième",
        19: "à la dix-neuvième",
        20: "à la vingtième",
        21: "à la vingt-et-unième",
        22: "à la vingt-deuxième",
        23: "à la vingt-troisième",
        24: "à la vingt-quatrième",
        25: "à la vingt-cinquième",
        26: "à la vingt-sixième",
        27: "à la vingt-septième",
        28: "à la vingt-huitième",
        29: "à la vingt-neuvième",
        30: "à la trentième",
    },
}

# Langues 
LANGUAGES = [
    {'code': 'fr', 'name': _('French')},
    {'code': 'en', 'name': _('English')},
    {'code': 'es', 'name': _('Spanish')},
]

# Thèmes
THEMES = [
    {'code': 'light', 'name': _('Clair')},
    {'code': 'dark', 'name': _('Sombre')},
    {'code': 'system', 'name': _('Système')}
]

# Couleurs
COLORS = [
    {'code': 'fonce', 'name': _('Vert émeraude')},
    {'code': 'clair', 'name': _('Vert pomme')},
    {'code': 'cyan', 'name': _('Cyan')},
    {'code': 'gris', 'name': _('Gris')},
]

# Civilités
CIVILITIES = [
    {'code': 'M', 'name': _('Monsieur')},
    {'code': 'F', 'name': _('Madame')},
    {'code': 'N', 'name': _('Neutre')},
]

# Timezones
TIMEZONES = [
    {'code': 'Pacific/Midway', 'name': 'Midway (UTC-11:00)'},
    {'code': 'America/Adak', 'name': 'Adak (UTC-10:00)'},
    {'code': 'Pacific/Honolulu', 'name': 'Honolulu (UTC-10:00)'},
    {'code': 'America/Anchorage', 'name': 'Anchorage (UTC-09:00)'},
    {'code': 'America/Los_Angeles', 'name': 'Los Angeles (UTC-08:00)'},
    {'code': 'America/Denver', 'name': 'Denver (UTC-07:00)'},
    {'code': 'America/Chicago', 'name': 'Chicago (UTC-06:00)'},
    {'code': 'America/New_York', 'name': 'New York (UTC-05:00)'},
    {'code': 'America/Caracas', 'name': 'Caracas (UTC-04:30)'},
    {'code': 'America/Halifax', 'name': 'Halifax (UTC-04:00)'},
    {'code': 'America/St_Johns', 'name': 'St. Johns (UTC-03:30)'},
    {'code': 'America/Argentina/Buenos_Aires', 'name': 'Buenos Aires (UTC-03:00)'},
    {'code': 'Atlantic/Azores', 'name': 'Azores (UTC-01:00)'},
    {'code': 'Europe/London', 'name': 'London (UTC+00:00)'},
    {'code': 'Europe/Paris', 'name': 'Paris (UTC+01:00)'},
    {'code': 'Europe/Athens', 'name': 'Athens (UTC+02:00)'},
    {'code': 'Africa/Nairobi', 'name': 'Nairobi (UTC+03:00)'},
    {'code': 'Europe/Moscow', 'name': 'Moscow (UTC+03:00)'},
    {'code': 'Asia/Tehran', 'name': 'Tehran (UTC+03:30)'},
    {'code': 'Asia/Dubai', 'name': 'Dubai (UTC+04:00)'},
    {'code': 'Asia/Kabul', 'name': 'Kabul (UTC+04:30)'},
    {'code': 'Asia/Karachi', 'name': 'Karachi (UTC+05:00)'},
    {'code': 'Asia/Kolkata', 'name': 'Kolkata (UTC+05:30)'},
    {'code': 'Asia/Kathmandu', 'name': 'Kathmandu (UTC+05:45)'},
]
    
# Genre et rôle pour les titres des membres du conseil
ROLE_TRANSLATIONS = {
    "Monsieur": {
        "Maire": "Maire",
        "Adjoint au maire": "Adjoint au maire",
        "Conseiller municipal": "Conseiller municipal",
        "Président": "Président",
        "Vice-président": "Vice-président",
        "Membre": "Membre",
        "Chargé de commission": "Chargé de commission",
    },
    "Madame": {
        "Maire": "Maire",
        "Adjoint au maire": "Adjointe au maire",
        "Conseiller municipal": "Conseillère municipale",
        "Président": "Présidente",
        "Vice-président": "Vice-présidente",
        "Membre": "Membre",
        "Chargé de commission": "Chargée de commission",
    },
    "Neutre": {
        "Maire": "Maire",
        "Adjoint au maire": "Adjoint(e) au maire",
        "Conseiller municipal": "Conseiller(e) municipal(e)",
        "Président": "président(e)",
        "Vice-président": "vice-président(e)",
        "Membre": "Membre",
        "Chargé de commission": "Chargé(e) de commission",
    },
    "Pluriel": {
        "Maire": "Maires",
        "Adjoint au maire": "Adjoints au maire",
        "Conseiller municipal": "Conseillers municipaux",
        "Président": "Présidents",
        "Vice-président": "Vice-présidents",
        "Membre": "Membres",
        "Chargé de commission": "Chargés de commission",
    }
}

# Table de correspondance pour les extensions de fichier connues
FILE_EXTENSIONS = {
    # Fichier texte et documents
    "doc": ("doc", "Document Word"),
    "docx": ("doc", "Document Word"),
    "odt": ("doc", "Document Writer"),
    "ott": ("doc", "Document Writer"),
    "txt": ("doc", "Fichier texte"),
    "rtf": ("doc", "Document RTF"),    
    "md": ("doc", "Document Markdown"),
    "tex": ("doc", "Document LaTeX"),
    "asc": ("doc", "Document ASCII"),
    
    # Tableurs et feuilles de calcul
    "xls": ("calc", "Feuille Excel"),
    "xlsx": ("calc", "Feuille Excel"),
    "ods": ("calc", "Feuille Calc"),
    "ots": ("calc", "Feuille Calc"),
    "csv": ("calc", "Fichier CSV"),
    "xlsm": ("calc", "Feuille Excel avec macro"),
    "tsv": ("calc", "Fichier TSV"),    
    "numbers": ("calc", "Feuille Numbers"),
    "xlr": ("calc", "Feuille Lotus 1-2-3"),
    "wk1": ("calc", "Feuille Lotus 1-2-3"),
    "wk2": ("calc", "Feuille Lotus 1-2-3"),
    "wk3": ("calc", "Feuille Lotus 1-2-3"),
    "wks": ("calc", "Feuille Lotus 1-2-3"),
    "123": ("calc", "Feuille Lotus 1-2-3"),
    
    # Fichiers de présentation
    "ppt": ("slide", "Présentation PowerPoint"),
    "pptx": ("slide", "Présentation PowerPoint"),
    "odp": ("slide", "Présentation Impress"),
    "otp": ("slide", "Présentation Impress"),
    "pps": ("slide", "Diaporama PowerPoint"),
    "ppsx": ("slide", "Diaporama PowerPoint"),
    "key": ("slide", "Présentation Keynote"),
    "odg": ("slide", "Dessin Draw"),
    "otg": ("slide", "Dessin Draw"),
    
    # Fichiers PDF
    "pdf": ("pdf", "Document PDF"),
    "ps": ("pdf", "Document PostScript"),
    "eps": ("pdf", "Document EPS"),
 
    # Fichiers images
    "png": ("image", "Image PNG"),
    "jpg": ("image", "Image JPG"),
    "jpeg": ("image", "Image JPEG"),
    "gif": ("image", "Image GIF"),
    "bmp": ("image", "Image BMP"),
    "tiff": ("image", "Image TIFF"),
    "svg": ("image", "Image SVG"),
    "ico": ("image", "Image ICO"),
    "webp": ("image", "Image WEBP"),
    "tif": ("image", "Image TIFF"),
    
    # Fichiers audio
    "mp3": ("audio", "Audio MP3"),
    "wav": ("audio", "Audio WAV"),
    "flac": ("audio", "Audio FLAC"),
    "ogg": ("audio", "Audio OGG"),
    "wma": ("audio", "Audio WMA"),
    "aac": ("audio", "Audio AAC"),
    "m4a": ("audio", "Audio M4A"),
    "opus": ("audio", "Audio OPUS"),   
    
    # Fichiers vidéo 
    "mp4": ("video", "Vidéo MP4"),
    "avi": ("video", "Vidéo AVI"),
    "mkv": ("video", "Vidéo MKV"),
    "mov": ("video", "Vidéo MOV"),
    "flv": ("video", "Vidéo FLV"),
    "webm": ("video", "Vidéo WEBM"),
    "ogg": ("video", "Vidéo OGG"),    
    
    # Fichiers compressés
    "zip": ("archive", "Archive ZIP"),
    "rar": ("archive", "Archive RAR"),
    "tar": ("archive", "Archive TAR"),
    "gz": ("archive", "Archive GZIP"),
    "7z": ("archive", "Archive 7z"),
    "bz2": ("archive", "Archive BZIP2"),
    "xz": ("archive", "Archive XZ"),
    
    # Programmation, scripts et bases de données
    "html": ("code", "Document HTML"),
    "xml": ("code", "Document XML"),
    "json": ("code", "Fichier JSON"),
    "yaml": ("code", "Fichier YAML"),
    "log": ("code", "Fichier journal"),
    "bat": ("code", "Script batch"),
    "sh": ("code", "Script Shell"),
    "py": ("code", "Script Python"),
    "java": ("code", "Fichier Java"),
    "c": ("code", "Fichier source C"),
    "cpp": ("code", "Fichier source C++"),
    "h": ("code", "Fichier en-tête"),
    "hpp": ("code", "Fichier en-tête C++"),
    "css": ("code", "Fichier CSS"),
    "scss": ("code", "Fichier SCSS"),
    "js": ("code", "Fichier JavaScript"),
    "ts": ("code", "Fichier TypeScript"),
    "php": ("code", "Script PHP"),
    "asp": ("code", "Script ASP"),
    "jsp": ("code", "Script JSP"),
    "sql": ("code", "Fichier SQL"),
    "mdb": ("code", "Base Access"),
    "accdb": ("code", "Base Access"),
    "db": ("code", "Base données"),
    "sqlite": ("code", "Base SQLite"),
    "yml": ("code", "Fichier YAML"),
    
    # Fichiers exécutables et d'installation
    "exe": ("system", "Exécutable Windows"),
    "msi": ("system", "Installation Windows"),
    "deb": ("system", "Paquet Debian"),
    "rpm": ("system", "Paquet RPM"),
    "apk": ("system", "Paquet Android"),
    "appimage": ("system", "Paquet AppImage"),  
    "iso": ("system", "Image ISO"),
    "img": ("system", "Image IMG"),
    "dmg": ("system", "Image DMG"),      
    "bak": ("system", "Fichier sauvegarde"),
    "tmp": ("system", "Fichier temporaire"),
    "ini": ("system", "Fichier configuration"),
    "cfg": ("system", "Fichier configuration"),
    "conf": ("system", "Fichier configuration"),
    "bat": ("system", "Script batch"),
    "sh": ("system", "Script Shell"),
    "ps1": ("system", "Script PowerShell"),
    "cmd": ("system", "Script CMD"),
    "dll": ("system", "Bibliothèque DLL"),
    "sys": ("system", "Fichier système"),
    "jar": ("system", "Fichier JAR"),
    "com": ("system", "Fichier COM"),
    "vbs": ("system", "Script VBScript"),
    
    # Livres électroniques
    "epub": ("ebook", "Livre EPUB"),
    "mobi": ("ebook", "Livre Mobipocket"),
    "azw": ("ebook", "Format Kindle"),
    "djvu": ("ebook", "Document DjVu"),
    "fb2": ("ebook", "Livre FictionBook"),
    "lit": ("ebook", "Ebook Microsoft Reader"),
}
  
# Mots à ne pas récupérer pour génération automatique de titres, slugs, etc.
STOP_WORDS = set(
    [
        "a",
        "à",
        "â",
        "abord",
        "afin",
        "ah",
        "ai",
        "aie",
        "ainsi",
        "allaient",
        "allo",
        "allô",
        "allons",
        "après",
        "assez",
        "attendu",
        "au",
        "aucun",
        "aucune",
        "aujourd",
        "aujourd'hui",
        "auquel",
        "aura",
        "auront",
        "aussi",
        "autre",
        "autres",
        "aux",
        "auxquelles",
        "auxquels",
        "avaient",
        "avais",
        "avait",
        "avant",
        "avec",
        "avoir",
        "bon",
        "car",
        "ce",
        "ceci",
        "cela",
        "celle",
        "celle-ci",
        "celle-là",
        "celles",
        "celles-ci",
        "celles-là",
        "celui",
        "celui-ci",
        "celui-là",
        "cent",
        "cependant",
        "certain",
        "certaine",
        "certaines",
        "certains",
        "certes",
        "ces",
        "cet",
        "cette",
        "ceux",
        "ceux-ci",
        "ceux-là",
        "chacun",
        "chaque",
        "cher",
        "chère",
        "chères",
        "chers",
        "chez",
        "ci",
        "combien",
        "comme",
        "comment",
        "d",
        "da",
        "dans",
        "de",
        "debout",
        "dedans",
        "dehors",
        "delà",
        "depuis",
        "derrière",
        "des",
        "dès",
        "désormais",
        "desquelles",
        "desquels",
        "dessous",
        "dessus",
        "deux",
        "deuxième",
        "deuxièmement",
        "devant",
        "devers",
        "devra",
        "différent",
        "différente",
        "différentes",
        "différents",
        "dire",
        "divers",
        "diverse",
        "diverses",
        "dix",
        "dix-huit",
        "dixième",
        "dix-neuf",
        "dix-sept",
        "doit",
        "doivent",
        "donc",
        "dont",
        "douze",
        "douzième",
        "dring",
        "du",
        "duquel",
        "elle",
        "elle-même",
        "elles",
        "elles-mêmes",
        "en",
        "entre",
        "environ",
        "es",
        "ès",
        "est",
        "et",
        "étaient",
        "étais",
        "était",
        "étant",
        "etc",
        "été",
        "etre",
        "être",
        "eu",
        "euh",
        "eux",
        "eux-mêmes",
        "excepté",
        "hé",
        "hormis",
        "hors",
        "huit",
        "huitième",
        "il",
        "ils",
        "j",
        "je",
        "jusqu",
        "jusque",
        "la",
        "là",
        "laquelle",
        "las",
        "le",
        "lequel",
        "les",
        "lès",
        "lesquelles",
        "lesquels",
        "leur",
        "leurs",
        "longtemps",
        "lorsque",
        "lui",
        "lui-même",
        "ma",
        "maint",
        "mais",
        "malgré",
        "me",
        "même",
        "mêmes",
        "mes",
        "mien",
        "mienne",
        "miennes",
        "miens",
        "moi",
        "moi-même",
        "moins",
        "mon",
        "moyennant",
        "n",
        "na",
        "ne",
        "néanmoins",
        "neuf",
        "neuvième",
        "ni",
        "non",
        "nos",
        "notre",
        "nôtre",
        "nôtres",
        "nous",
        "nous-mêmes",
        "nul",
        "o",
        "ô",
        "oh",
        "on",
        "ont",
        "onze",
        "onzième",
        "or",
        "ou",
        "où",
        "outre",
        "par",
        "parmi",
        "partant",
        "pas",
        "passé",
        "pendant",
        "personne",
        "peu",
        "plein",
        "plus",
        "plusieurs",
        "plutôt",
        "pour",
        "pourquoi",
        "premier",
        "première",
        "premièrement",
        "près",
        "proche",
        "psitt",
        "puisque",
        "qu",
        "quand",
        "quant",
        "quanta",
        "quarante",
        "quatorze",
        "quatre",
        "quatre-vingt",
        "quatrième",
        "quatrièmement",
        "que",
        "quel",
        "quelconque",
        "quelle",
        "quelles",
        "quelque",
        "quelques",
        "quels",
        "qui",
        "quiconque",
        "quinze",
        "quoi",
        "quoique",
        "revoici",
        "revoilà",
        "s",
        "sa",
        "sans",
        "sauf",
        "se",
        "seize",
        "selon",
        "sept",
        "septième",
        "sera",
        "serai",
        "seraient",
        "serais",
        "serait",
        "seras",
        "serez",
        "seriez",
        "serions",
        "serons",
        "seront",
        "ses",
        "si",
        "sien",
        "sienne",
        "siennes",
        "siens",
        "sinon",
        "six",
        "sixième",
        "soi",
        "soi-même",
        "soit",
        "soixante",
        "son",
        "sont",
        "sous",
        "suivant",
        "sur",
        "ta",
        "te",
        "tes",
        "tien",
        "tienne",
        "tiennes",
        "tiens",
        "toi",
        "toi-même",
        "ton",
        "treize",
        "trois",
        "troisième",
        "troisièmement",
        "trop",
        "tu",
        "un",
        "une",
        "unes",
        "uns",
        "v",
        "vers",
        "voici",
        "voilà",
        "vos",
        "votre",
        "vôtre",
        "vôtres",
        "vous",
        "vous-mêmes",
        "vu",
        "y",
        "zut",
    ]
)


#######################
## OBSOLETES(CHARTS) ##
####################### 

# # Type de graphiques
# CHART_TYPES = (
#     ('line', 'Graphique linéaire'),
#     ('bar', 'Graphique à barres verticales'),
#     ('bar_horizontal', 'Graphique à barres horizontales'),
#     ('area', 'Graphique en aires'),
#     ('multi', 'Graphique combiné linéaire/barres/aires'),
#     ('pie', 'Graphique en secteurs'),
#     ('doughnut', 'Graphique en anneau'),
#     ('radar', 'Graphique radar'),
#     ('polar', 'Graphique polaire'),
#     ('waterfall', 'Graphique en cascade')
# )

# # Couleurs pour les graphiques
# CHART_COLORS = (
#     ('#ff0000', 'Rouge'),
#     ('#00ff00', 'Vert'),
#     ('#0000ff', 'Bleu'),
#     ('#ffff00', 'Jaune'),
#     ('#ff00ff', 'Magenta'),
#     ('#00ffff', 'Cyan'),
#     ('#808080', 'Gris'),
#     ('#800000', 'Marron'),
#     ('#008000', 'Vert foncé'),
#     ('#000080', 'Bleu foncé'),
#     ('#800080', 'Violet'),
#     ('#c0c0c0', 'Argent'),
#     ('#ff3399', 'Rose'),
#     ('#008080', 'Sarcelle'), # Teal
#     ('#00CED1', 'Turquoise foncé'), # DarkTurquoise
#     ('#7CFC00', 'Vert prairie'), # LawnGreen
#     ('#D2691E', 'Chocolat'), # Chocolate
#     ('#48D1CC', 'Turquoise moyen'), # MediumTurquoise
#     ('#BDB76B', 'Kaki foncé'), # DarkKhaki
#     ('#3CB371', 'Vert mer moyen'), # MediumSeaGreen
#     ('#66CDAA', 'Aquamarine moyen'), # MediumAquamarine
#     ('#FF7F50', 'Corail'), # Coral
# )
