# Type de graphiques
CHART_TYPES = (
    ('line', 'Graphique linéaire'),
    ('bar', 'Graphique à barres verticales'),
    ('bar_horizontal', 'Graphique à barres horizontales'),
    ('area', 'Graphique en aires'),
    ('multi', 'Graphique combiné linéaire/barres/aires'),
    ('pie', 'Graphique en secteurs'),
    ('doughnut', 'Graphique en anneau'),
    ('radar', 'Graphique radar'),
    ('polar', 'Graphique polaire'),
    ('waterfall', 'Graphique en cascade')
)

# Couleurs pour les graphiques
CHART_COLORS = (
    ('#ff0000', 'Rouge'),
    ('#00ff00', 'Vert'),
    ('#0000ff', 'Bleu'),
    ('#ffff00', 'Jaune'),
    ('#ff00ff', 'Magenta'),
    ('#00ffff', 'Cyan'),
    ('#808080', 'Gris'),
    ('#800000', 'Marron'),
    ('#008000', 'Vert foncé'),
    ('#000080', 'Bleu foncé'),
    ('#800080', 'Violet'),
    ('#c0c0c0', 'Argent'),
    ('#ff3399', 'Rose'),
    ('#008080', 'Sarcelle'), # Teal
    ('#00CED1', 'Turquoise foncé'), # DarkTurquoise
    ('#7CFC00', 'Vert prairie'), # LawnGreen
    ('#D2691E', 'Chocolat'), # Chocolate
    ('#48D1CC', 'Turquoise moyen'), # MediumTurquoise
    ('#BDB76B', 'Kaki foncé'), # DarkKhaki
    ('#3CB371', 'Vert mer moyen'), # MediumSeaGreen
    ('#66CDAA', 'Aquamarine moyen'), # MediumAquamarine
    ('#FF7F50', 'Corail'), # Coral
)

# Genre et rôle pour les titres des membres du conseil
ROLE_TRANSLATIONS = {
    "Monsieur": {
        "Maire": "Maire",
        "Adjoint au maire": "Adjoint au maire",
        "Conseiller municipal": "Conseiller municipal",
        "Président": "Président",
        "Vice-président": "Vice-président",
        "Membre": "Membre",
        "Chargé de commission": "Chargé de commission",
    },
    "Madame": {
        "Maire": "Maire",
        "Adjoint au maire": "Adjointe au maire",
        "Conseiller municipal": "Conseillère municipale",
        "Président": "Présidente",
        "Vice-président": "Vice-présidente",
        "Membre": "Membre",
        "Chargé de commission": "Chargée de commission",
    },
    "Neutre": {
        "Maire": "Maire",
        "Adjoint au maire": "Adjoint(e) au maire",
        "Conseiller municipal": "Conseiller(e) municipal(e)",
        "Président": "président(e)",
        "Vice-président": "vice-président(e)",
        "Membre": "Membre",
        "Chargé de commission": "Chargé(e) de commission",
    },
    "Pluriel": {
        "Maire": "Maires",
        "Adjoint au maire": "Adjoints au maire",
        "Conseiller municipal": "Conseillers municipaux",
        "Président": "Présidents",
        "Vice-président": "Vice-présidents",
        "Membre": "Membres",
        "Chargé de commission": "Chargés de commission",
    }
}


# Table de correspondance pour les extensions de fichier connues
extensions = {
    "doc": "Document Word",
    "docx": "Document Word",
    "xls": "Feuille Excel",
    "xlsx": "Feuille Excel",
    "ppt": "Présentation PowerPoint",
    "pptx": "Présentation PowerPoint",
    "pdf": "Document PDF",
    "png": "Image PNG",
    "jpg": "Image JPG",
    "jpeg": "Image JPEG",
    "gif": "Image GIF",
    "bmp": "Image BMP",
    "tiff": "Image TIFF",
    "svg": "Image SVG",
    "mp3": "Audio MP3",
    "mp4": "Vidéo MP4",
    "avi": "Vidéo AVI",
    "mkv": "Vidéo MKV",
    "mov": "Vidéo MOV",
    "flv": "Vidéo FLV",
    "webm": "Vidéo WEBM",
    "ogg": "Vidéo OGG",
    "zip": "Archive ZIP",
    "rar": "Archive RAR",
    "tar": "Archive TAR",
    "gz": "Archive GZIP",
    "7z": "Archive 7z",
    "bz2": "Archive BZIP2",
    "xz": "Archive XZ",
    "iso": "Image ISO",
    "img": "Image IMG",
    "dmg": "Image DMG",
    "exe": "Exécutable Windows",
    "msi": "Installation Windows",
    "deb": "Paquet Debian",
    "rpm": "Paquet RPM",
    "apk": "Paquet Android",
    "appimage": "Paquet AppImage",
    "odt": "Document Writer",
    "ott": "Document Writer",
    "ods": "Feuille Calc",
    "ots": "Feuille Calc",
    "odp": "Présentation Impress",
    "otp": "Présentation Impress",
    "odg": "Dessin Draw",
    "otg": "Dessin Draw",
    "odf": "Formule Math",
    "otf": "Formule Math",
    "odb": "Base Base",
    "otb": "Base Base",
    "odm": "Document Master",
    "oth": "Document Master",
    "odc": "Document Chart",
    "otc": "Document Chart",
    "txt": "Fichier texte",
    "csv": "Fichier CSV",
    "rtf": "Document RTF",
    "html": "Document HTML",
    "xml": "Document XML",
    "json": "Fichier JSON",
    "yaml": "Fichier YAML",
    "log": "Fichier journal",
    "bat": "Script batch",
    "sh": "Script Shell",
    "py": "Script Python",
    "java": "Fichier Java",
    "c": "Fichier source C",
    "cpp": "Fichier source C++",
    "h": "Fichier en-tête",
    "hpp": "Fichier en-tête C++",
    "css": "Fichier CSS",
    "scss": "Fichier SCSS",
    "js": "Fichier JavaScript",
    "ts": "Fichier TypeScript",
    "php": "Script PHP",
    "asp": "Script ASP",
    "jsp": "Script JSP",
    "sql": "Fichier SQL",
    "mdb": "Base Access",
    "accdb": "Base Access",
    "db": "Base données",
    "sqlite": "Base SQLite",
    "bak": "Fichier sauvegarde",
    "tmp": "Fichier temporaire",
    "ini": "Fichier configuration",
    "cfg": "Fichier configuration",
    "conf": "Fichier configuration",
    "yaml": "Fichier YAML",
    "yml": "Fichier YAML",
    "epub": "Livre EPUB",
    "mobi": "Livre Mobipocket",
    "azw": "Format Kindle",
    "djvu": "Document DjVu",
    "fb2": "Livre FictionBook",
    "lit": "Ebook Microsoft Reader",
    "pdb": "Format PalmDOC",
    "prc": "Format PalmDOC",
    "xps": "Document XPS",
    "ps": "Document PostScript",
    "tex": "Document LaTeX",
    "xlsm": "Feuille Excel avec macro",
    "tsv": "Fichier TSV",
}
  
# Mots à ne pas récupérer pour génération automatique de titres, slugs, etc.
STOP_WORDS = set(
    [
        "a",
        "à",
        "â",
        "abord",
        "afin",
        "ah",
        "ai",
        "aie",
        "ainsi",
        "allaient",
        "allo",
        "allô",
        "allons",
        "après",
        "assez",
        "attendu",
        "au",
        "aucun",
        "aucune",
        "aujourd",
        "aujourd'hui",
        "auquel",
        "aura",
        "auront",
        "aussi",
        "autre",
        "autres",
        "aux",
        "auxquelles",
        "auxquels",
        "avaient",
        "avais",
        "avait",
        "avant",
        "avec",
        "avoir",
        "bon",
        "car",
        "ce",
        "ceci",
        "cela",
        "celle",
        "celle-ci",
        "celle-là",
        "celles",
        "celles-ci",
        "celles-là",
        "celui",
        "celui-ci",
        "celui-là",
        "cent",
        "cependant",
        "certain",
        "certaine",
        "certaines",
        "certains",
        "certes",
        "ces",
        "cet",
        "cette",
        "ceux",
        "ceux-ci",
        "ceux-là",
        "chacun",
        "chaque",
        "cher",
        "chère",
        "chères",
        "chers",
        "chez",
        "ci",
        "combien",
        "comme",
        "comment",
        "d",
        "da",
        "dans",
        "de",
        "debout",
        "dedans",
        "dehors",
        "delà",
        "depuis",
        "derrière",
        "des",
        "dès",
        "désormais",
        "desquelles",
        "desquels",
        "dessous",
        "dessus",
        "deux",
        "deuxième",
        "deuxièmement",
        "devant",
        "devers",
        "devra",
        "différent",
        "différente",
        "différentes",
        "différents",
        "dire",
        "divers",
        "diverse",
        "diverses",
        "dix",
        "dix-huit",
        "dixième",
        "dix-neuf",
        "dix-sept",
        "doit",
        "doivent",
        "donc",
        "dont",
        "douze",
        "douzième",
        "dring",
        "du",
        "duquel",
        "elle",
        "elle-même",
        "elles",
        "elles-mêmes",
        "en",
        "entre",
        "environ",
        "es",
        "ès",
        "est",
        "et",
        "étaient",
        "étais",
        "était",
        "étant",
        "etc",
        "été",
        "etre",
        "être",
        "eu",
        "euh",
        "eux",
        "eux-mêmes",
        "excepté",
        "hé",
        "hormis",
        "hors",
        "huit",
        "huitième",
        "il",
        "ils",
        "j",
        "je",
        "jusqu",
        "jusque",
        "la",
        "là",
        "laquelle",
        "las",
        "le",
        "lequel",
        "les",
        "lès",
        "lesquelles",
        "lesquels",
        "leur",
        "leurs",
        "longtemps",
        "lorsque",
        "lui",
        "lui-même",
        "ma",
        "maint",
        "mais",
        "malgré",
        "me",
        "même",
        "mêmes",
        "mes",
        "mien",
        "mienne",
        "miennes",
        "miens",
        "moi",
        "moi-même",
        "moins",
        "mon",
        "moyennant",
        "n",
        "na",
        "ne",
        "néanmoins",
        "neuf",
        "neuvième",
        "ni",
        "non",
        "nos",
        "notre",
        "nôtre",
        "nôtres",
        "nous",
        "nous-mêmes",
        "nul",
        "o",
        "ô",
        "oh",
        "on",
        "ont",
        "onze",
        "onzième",
        "or",
        "ou",
        "où",
        "outre",
        "par",
        "parmi",
        "partant",
        "pas",
        "passé",
        "pendant",
        "personne",
        "peu",
        "plein",
        "plus",
        "plusieurs",
        "plutôt",
        "pour",
        "pourquoi",
        "premier",
        "première",
        "premièrement",
        "près",
        "proche",
        "psitt",
        "puisque",
        "qu",
        "quand",
        "quant",
        "quanta",
        "quarante",
        "quatorze",
        "quatre",
        "quatre-vingt",
        "quatrième",
        "quatrièmement",
        "que",
        "quel",
        "quelconque",
        "quelle",
        "quelles",
        "quelque",
        "quelques",
        "quels",
        "qui",
        "quiconque",
        "quinze",
        "quoi",
        "quoique",
        "revoici",
        "revoilà",
        "s",
        "sa",
        "sans",
        "sauf",
        "se",
        "seize",
        "selon",
        "sept",
        "septième",
        "sera",
        "serai",
        "seraient",
        "serais",
        "serait",
        "seras",
        "serez",
        "seriez",
        "serions",
        "serons",
        "seront",
        "ses",
        "si",
        "sien",
        "sienne",
        "siennes",
        "siens",
        "sinon",
        "six",
        "sixième",
        "soi",
        "soi-même",
        "soit",
        "soixante",
        "son",
        "sont",
        "sous",
        "suivant",
        "sur",
        "ta",
        "te",
        "tes",
        "tien",
        "tienne",
        "tiennes",
        "tiens",
        "toi",
        "toi-même",
        "ton",
        "treize",
        "trois",
        "troisième",
        "troisièmement",
        "trop",
        "tu",
        "un",
        "une",
        "unes",
        "uns",
        "v",
        "vers",
        "voici",
        "voilà",
        "vos",
        "votre",
        "vôtre",
        "vôtres",
        "vous",
        "vous-mêmes",
        "vu",
        "y",
        "zut",
    ]
)
