# Generated by Django 5.0 on 2024-04-15 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_formpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancedformsetting',
            name='to_subject',
            field=models.CharField(blank=True, default='Nouvelle soumission', help_text='Subject of the email.', max_length=255, null=True, verbose_name='Subject'),
        ),
        migrations.AddField(
            model_name='advancedformsetting',
            name='unique',
            field=models.BooleanField(default=False, help_text='Allow only one submission per user.', verbose_name='Unique submission'),
        ),
        migrations.AlterField(
            model_name='advancedformsetting',
            name='to_address',
            field=models.EmailField(help_text='Email address to send the form submission to.', max_length=254, verbose_name='To address'),
        ),
    ]
