# Generated by Django 5.0 on 2024-04-15 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_contactpage_tooltip_alter_formpage_tooltip_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advancedformsetting',
            old_name='to_subject',
            new_name='subject',
        ),
    ]
