# Generated by Django 5.0.4 on 2024-04-17 04:20

import wagtail.blocks
import wagtail.fields
import wagtailstreamforms.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_to_subject_advancedformsetting_subject'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormPage',
            new_name='HomeFormPage',
        ),
        migrations.AlterModelOptions(
            name='contactpage',
            options={'verbose_name': 'Administration Form page (survey, form, etc.)', 'verbose_name_plural': 'Form pages'},
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='inscription_form',
        ),
        migrations.AddField(
            model_name='contactpage',
            name='form',
            field=wagtail.fields.StreamField([('form_field', wagtail.blocks.StructBlock([('form', wagtailstreamforms.blocks.FormChooserBlock()), ('form_action', wagtail.blocks.CharBlock(help_text='The form post action. "" or "." for the current page or a url', required=False)), ('form_reference', wagtailstreamforms.blocks.InfoBlock(help_text='This form will be given a unique reference once saved', required=False))], icon='form', label='Form field'))], blank=True, help_text='The main form for allow people to contact intranet administrators.', null=True, verbose_name='Contact form'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='introduction',
            field=wagtail.fields.RichTextField(blank=True, help_text='Here you can explain how the contact form works...', null=True, verbose_name='Introduction'),
        ),
    ]
