# Generated by Django 5.0 on 2024-03-18 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intraneticons',
            name='administration',
        ),
        migrations.RemoveField(
            model_name='intraneticons',
            name='amicale',
        ),
        migrations.RemoveField(
            model_name='intraneticons',
            name='base_item',
        ),
        migrations.RemoveField(
            model_name='intraneticons',
            name='faq',
        ),
        migrations.RemoveField(
            model_name='intraneticons',
            name='ressources',
        ),
        migrations.AddField(
            model_name='intraneticons',
            name='copy',
            field=models.ForeignKey(blank=True, help_text='Copy to clipboard', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='Copy to clipboard'),
        ),
        migrations.AddField(
            model_name='intraneticons',
            name='instant_download',
            field=models.ForeignKey(blank=True, help_text='Documents (InstantDownload)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='Download'),
        ),
        migrations.AddField(
            model_name='intraneticons',
            name='print',
            field=models.ForeignKey(blank=True, help_text='Print', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='Print'),
        ),
        migrations.AlterField(
            model_name='intraneticons',
            name='download',
            field=models.ForeignKey(blank=True, help_text='Download', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='Download'),
        ),
    ]
