# Generated by Django 5.0 on 2024-04-10 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_intraneticons_categories'),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intraneticons',
            name='compress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='Compress'),
        ),
        migrations.AddField(
            model_name='intraneticons',
            name='expand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='Expand'),
        ),
        migrations.AddField(
            model_name='intraneticons',
            name='maximize',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='Maximize'),
        ),
        migrations.AddField(
            model_name='intraneticons',
            name='minimize',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='Minimize'),
        ),
        migrations.AddField(
            model_name='intraneticons',
            name='page_down',
            field=models.ForeignKey(blank=True, help_text='Header icon to go to the next page in viewers (PDF, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='Page Down'),
        ),
        migrations.AddField(
            model_name='intraneticons',
            name='page_down_max',
            field=models.ForeignKey(blank=True, help_text='Header icon to go to the last page in viewers (PDF, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='Page Down Max'),
        ),
        migrations.AddField(
            model_name='intraneticons',
            name='page_up',
            field=models.ForeignKey(blank=True, help_text='Header icon to go to the previous page in viewers (PDF, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='Page Up'),
        ),
        migrations.AddField(
            model_name='intraneticons',
            name='page_up_max',
            field=models.ForeignKey(blank=True, help_text='Header icon to go to the first page in viewers (PDF, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='Page Up Max'),
        ),
    ]
