# Generated by Django 5.0 on 2024-04-04 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_intraneticons_administration_and_more'),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intraneticons',
            name='ol_item',
            field=models.ForeignKey(blank=True, help_text='Ordered list item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='Ordered list item'),
        ),
        migrations.AddField(
            model_name='intraneticons',
            name='ul_item',
            field=models.ForeignKey(blank=True, help_text='Unordered list item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='Unordered list item'),
        ),
    ]
