# Generated by Django 5.0 on 2024-04-04 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_intraneticons_ol_item_intraneticons_ul_item'),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intraneticons',
            name='next_page',
        ),
        migrations.RemoveField(
            model_name='intraneticons',
            name='ol_item',
        ),
        migrations.RemoveField(
            model_name='intraneticons',
            name='previous_page',
        ),
        migrations.AddField(
            model_name='intraneticons',
            name='calendar_next_page',
            field=models.ForeignKey(blank=True, help_text='Icon in the calendar section to go to the next page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='Next Page'),
        ),
        migrations.AddField(
            model_name='intraneticons',
            name='calendar_previous_page',
            field=models.ForeignKey(blank=True, help_text='Icon in the calendar section to go to the previous page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='Previous Page'),
        ),
        migrations.AddField(
            model_name='intraneticons',
            name='ol_item_1',
            field=models.ForeignKey(blank=True, help_text='Ordered list first item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='OL-1'),
        ),
        migrations.AddField(
            model_name='intraneticons',
            name='ol_item_2',
            field=models.ForeignKey(blank=True, help_text='Ordered list item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='OL-2'),
        ),
        migrations.AddField(
            model_name='intraneticons',
            name='ol_item_3',
            field=models.ForeignKey(blank=True, help_text='Ordered list item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='OL-3'),
        ),
        migrations.AddField(
            model_name='intraneticons',
            name='ol_item_4',
            field=models.ForeignKey(blank=True, help_text='Ordered list item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='OL-4'),
        ),
        migrations.AddField(
            model_name='intraneticons',
            name='ol_item_5',
            field=models.ForeignKey(blank=True, help_text='Ordered list item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='OL-5'),
        ),
        migrations.AddField(
            model_name='intraneticons',
            name='ol_item_6',
            field=models.ForeignKey(blank=True, help_text='Ordered list item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='OL-6'),
        ),
        migrations.AddField(
            model_name='intraneticons',
            name='ol_item_7',
            field=models.ForeignKey(blank=True, help_text='Ordered list item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='OL-7'),
        ),
        migrations.AddField(
            model_name='intraneticons',
            name='ol_item_8',
            field=models.ForeignKey(blank=True, help_text='Ordered list item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='OL-8'),
        ),
        migrations.AddField(
            model_name='intraneticons',
            name='ol_item_9',
            field=models.ForeignKey(blank=True, help_text='Ordered list item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='OL-9'),
        ),
        migrations.AlterField(
            model_name='intraneticons',
            name='amicale_divers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='Amicale divers'),
        ),
        migrations.AlterField(
            model_name='intraneticons',
            name='amicale_news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='Amicale news'),
        ),
        migrations.AlterField(
            model_name='intraneticons',
            name='amicale_none',
            field=models.ForeignKey(blank=True, help_text='Amicale unknown page type icon', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='Amicale unknown'),
        ),
        migrations.AlterField(
            model_name='intraneticons',
            name='amicale_sorties',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='Amicale sorties'),
        ),
        migrations.AlterField(
            model_name='intraneticons',
            name='next_item',
            field=models.ForeignKey(blank=True, help_text='Footer icon to nvaigate (right) in the list', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='Next Item'),
        ),
        migrations.AlterField(
            model_name='intraneticons',
            name='previous_item',
            field=models.ForeignKey(blank=True, help_text='Footer icon to nvaigate (left) in the list', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='Previous Item'),
        ),
        migrations.AlterField(
            model_name='intraneticons',
            name='ul_item',
            field=models.ForeignKey(blank=True, help_text='Icon preceding the item label', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='Unordered list item'),
        ),
        migrations.AlterField(
            model_name='intraneticons',
            name='user_profile',
            field=models.ForeignKey(blank=True, help_text='User profile', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='Header top-right icon'),
        ),
    ]
