# Generated by Django 5.0 on 2024-04-05 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_intraneticons_next_page_and_more'),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intraneticons',
            name='law_text',
            field=models.ForeignKey(blank=True, help_text='FAQ page, law text icon', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='Law text'),
        ),
        migrations.AddField(
            model_name='intraneticons',
            name='tags',
            field=models.ForeignKey(blank=True, help_text='Tag icon for numerous pages', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='Tags'),
        ),
    ]
