# Generated by Django 5.0 on 2024-04-12 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_intraneticons_home_all_intraneticons_home_none'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intraneticons',
            old_name='instant_download',
            new_name='home_download',
        ),
        migrations.RenameField(
            model_name='intraneticons',
            old_name='form',
            new_name='home_form',
        ),
        migrations.RenameField(
            model_name='intraneticons',
            old_name='generic',
            new_name='home_generic',
        ),
    ]
