# Generated by Django 5.0 on 2024-04-13 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_rename_instant_download_intraneticons_home_download_and_more'),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intraneticons',
            name='home',
            field=models.ForeignKey(blank=True, help_text="'Home' symbol to back to the home page.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='Home'),
        ),
    ]
