# Generated by Django 5.0 on 2024-04-14 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_intraneticons_home'),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intraneticons',
            name='inscription',
            field=models.ForeignKey(blank=True, help_text='Inscription form (Amicale, contact, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='Inscription'),
        ),
    ]
