# Generated by Django 5.0.4 on 2024-04-21 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_intraneticons_open_in_maps'),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intraneticons',
            name='archive_file',
            field=models.ForeignKey(blank=True, help_text='Archive icon', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='Archive'),
        ),
        migrations.AddField(
            model_name='intraneticons',
            name='audio_file',
            field=models.ForeignKey(blank=True, help_text='Audio icon', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='Audio'),
        ),
        migrations.AddField(
            model_name='intraneticons',
            name='calc_file',
            field=models.ForeignKey(blank=True, help_text='Excel icon', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='Excel'),
        ),
        migrations.AddField(
            model_name='intraneticons',
            name='doc_file',
            field=models.ForeignKey(blank=True, help_text='DOC icon', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='DOC'),
        ),
        migrations.AddField(
            model_name='intraneticons',
            name='image_file',
            field=models.ForeignKey(blank=True, help_text='Image icon', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='intraneticons',
            name='pdf_file',
            field=models.ForeignKey(blank=True, help_text='PDF icon', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='PDF'),
        ),
        migrations.AddField(
            model_name='intraneticons',
            name='slide_file',
            field=models.ForeignKey(blank=True, help_text='Powerpoint icon', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='Powerpoint'),
        ),
        migrations.AddField(
            model_name='intraneticons',
            name='unknown_file',
            field=models.ForeignKey(blank=True, help_text='Unknown file icon', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='Unknown file'),
        ),
        migrations.AddField(
            model_name='intraneticons',
            name='video_file',
            field=models.ForeignKey(blank=True, help_text='Video icon', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='Video'),
        ),
    ]
