# Generated by Django 5.0.4 on 2024-04-21 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_intraneticons_archive_file_intraneticons_audio_file_and_more'),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intraneticons',
            name='code_file',
            field=models.ForeignKey(blank=True, help_text='Code icon', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='Code'),
        ),
        migrations.AddField(
            model_name='intraneticons',
            name='ebook_file',
            field=models.ForeignKey(blank=True, help_text='Ebook icon', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='Ebook'),
        ),
        migrations.AddField(
            model_name='intraneticons',
            name='system_file',
            field=models.ForeignKey(blank=True, help_text='System icon', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='System'),
        ),
    ]
