# Generated by Django 5.0.4 on 2024-04-24 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_intraneticons_mail_to'),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intraneticons',
            name='star_out',
            field=models.ForeignKey(blank=True, help_text='Closing news section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='Star out'),
        ),
    ]
