# Generated by Django 5.0 on 2024-05-02 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_intraneticons_star_out'),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intraneticons',
            name='attachments_file',
            field=models.ForeignKey(blank=True, help_text='Mail attachments icon', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='Attachments'),
        ),
    ]
