# Generated by Django 5.0 on 2024-04-12 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amicale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amicalepage',
            name='type',
            field=models.CharField(blank=True, choices=[('autres', 'Divers'), ('sorties', 'Sorties'), ('news', 'Nouvelles')], default='autres', max_length=10, null=True, verbose_name="Type de l'article"),
        ),
    ]
