# Generated by Django 5.0 on 2024-04-15 06:52

import django.db.models.deletion
import modelcluster.fields
import wagtail.blocks
import wagtail.fields
import wagtailstreamforms.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amicale', '0003_amicaleinscriptionpage'),
        ('wagtaildocs', '0012_uploadeddocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='amicaleinscriptionpage',
            name='introduction',
            field=wagtail.fields.RichTextField(blank=True, help_text='Here you can explain how the inscription works...', null=True, verbose_name='Introduction'),
        ),
        migrations.AlterField(
            model_name='amicaleinscriptionpage',
            name='inscription_form',
            field=wagtail.fields.StreamField([('form_field', wagtail.blocks.StructBlock([('form', wagtailstreamforms.blocks.FormChooserBlock()), ('form_action', wagtail.blocks.CharBlock(help_text='The form post action. "" or "." for the current page or a url', required=False)), ('form_reference', wagtailstreamforms.blocks.InfoBlock(help_text='This form will be given a unique reference once saved', required=False))], icon='form', label='Form field'))], blank=True, help_text='The main form for the inscription to the amicale.', null=True, verbose_name='Inscription form'),
        ),
        migrations.CreateModel(
            name='AmicalePieceJointe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Title')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtaildocs.document', verbose_name='File')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscription_documents', to='amicale.amicaleinscriptionpage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
