# Generated by Django 5.0.4 on 2024-04-17 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amicale', '0005_alter_amicaleindexpage_tooltip_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amicaleinscriptionpage',
            old_name='inscription_form',
            new_name='form',
        ),
        migrations.RenameField(
            model_name='amicalepage',
            old_name='inscription_form',
            new_name='form',
        ),
    ]
