# Generated by Django 5.0.4 on 2024-04-19 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amicale', '0006_rename_inscription_form_amicaleinscriptionpage_form_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amicalepage',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='author',
            name='author_image',
        ),
        migrations.RemoveField(
            model_name='amicalepage',
            name='author',
        ),
        migrations.DeleteModel(
            name='AmicalePageTag',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
