# Generated by Django 5.0 on 2024-04-15 06:53

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_faqformpage'),
        ('wagtaildocs', '0012_uploadeddocument'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqformpage',
            options={'verbose_name': 'Agents Form page (survey, form, etc.)', 'verbose_name_plural': 'Form pages'},
        ),
        migrations.RemoveField(
            model_name='faqformpage',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='faqformpage',
            name='body',
        ),
        migrations.AddField(
            model_name='faqformpage',
            name='introduction',
            field=wagtail.fields.RichTextField(blank=True, help_text='Here you can explain the survey to agents.', null=True, verbose_name='Introduction'),
        ),
        migrations.CreateModel(
            name='AmicalePieceJointe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Title')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtaildocs.document', verbose_name='File')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents_documents', to='agents.faqformpage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
