# Generated by Django 5.0 on 2024-04-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_faqformpage_date_from_faqformpage_date_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqindexpage',
            name='tooltip',
            field=models.CharField(blank=True, help_text='Used for accessibility (alt, title) and when user mouse over the icon.', max_length=255, null=True, verbose_name='Tooltip.'),
        ),
    ]
