# Generated by Django 5.0.4 on 2024-04-17 04:20

import wagtail.blocks
import wagtail.fields
import wagtailstreamforms.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_alter_faqformpage_form_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqformpage',
            name='form',
            field=wagtail.fields.StreamField([('form_field', wagtail.blocks.StructBlock([('form', wagtailstreamforms.blocks.FormChooserBlock()), ('form_action', wagtail.blocks.CharBlock(help_text='The form post action. "" or "." for the current page or a url', required=False)), ('form_reference', wagtailstreamforms.blocks.InfoBlock(help_text='This form will be given a unique reference once saved', required=False))], icon='form', label='Form field'))], blank=True, help_text='The main form for to gather informations from the agents.', null=True, verbose_name='Question form'),
        ),
        migrations.AlterField(
            model_name='faqformpage',
            name='introduction',
            field=wagtail.fields.RichTextField(blank=True, help_text='Here you can explain how the gathering works...', null=True, verbose_name='Introduction'),
        ),
    ]
