# Generated by Django 5.0 on 2024-03-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='convocationpage',
            name='old',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Old'),
        ),
    ]
