# Generated by Django 5.0 on 2024-02-14 11:16

import django.db.models.deletion
import modelcluster.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        ('wagtailcore', '0092_query_searchpromotion_querydailyhits'),
        ('wagtaildocs', '0012_uploadeddocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='compterendupage',
            name='secretary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secretary_cr', to=settings.AUTH_USER_MODEL, verbose_name='Secrétaire'),
        ),
        migrations.AddField(
            model_name='compterendupage',
            name='substitute_users',
            field=models.ManyToManyField(blank=True, related_name='substitute_cr', to=settings.AUTH_USER_MODEL, verbose_name='Remplaçants'),
        ),
        migrations.AddField(
            model_name='compterendupiecejointe',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtaildocs.document', verbose_name='File'),
        ),
        migrations.AddField(
            model_name='compterendupiecejointe',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='compterendu_documents', to='administration.compterendupage'),
        ),
        migrations.AddField(
            model_name='conferencesindexpage',
            name='logo',
            field=models.ForeignKey(blank=True, help_text='𝐈𝐝𝐞𝐚𝐥 𝐟𝐨𝐫𝐦: Round or square (1/1). 𝐈𝐝𝐞𝐚𝐥 𝐟𝐨𝐫𝐦𝐚𝐭: Filled SVG. 𝐒𝐞𝐜𝐨𝐧𝐝𝐚𝐫𝐲 𝐟𝐨𝐫𝐦𝐚𝐭: PNG with transparent background.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='Logo (SVG, png, jpg, etc.)'),
        ),
        migrations.AddField(
            model_name='conseilsindexpage',
            name='logo',
            field=models.ForeignKey(blank=True, help_text='𝐈𝐝𝐞𝐚𝐥 𝐟𝐨𝐫𝐦: Round or square (1/1). 𝐈𝐝𝐞𝐚𝐥 𝐟𝐨𝐫𝐦𝐚𝐭: Filled SVG. 𝐒𝐞𝐜𝐨𝐧𝐝𝐚𝐫𝐲 𝐟𝐨𝐫𝐦𝐚𝐭: PNG with transparent background.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='Logo (SVG, png, jpg, etc.)'),
        ),
        migrations.AddField(
            model_name='compterendupage',
            name='convocation',
            field=models.OneToOneField(help_text='Sélectionnez la convocation associée.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.convocationpage', verbose_name='Convocation'),
        ),
        migrations.AddField(
            model_name='convocationpiecejointe',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtaildocs.document', verbose_name='File'),
        ),
        migrations.AddField(
            model_name='convocationpiecejointe',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='convocation_documents', to='administration.convocationpage'),
        ),
        migrations.AddField(
            model_name='convocationuser',
            name='alternate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convocation_user_alternates', to=settings.AUTH_USER_MODEL, verbose_name='Alternate'),
        ),
        migrations.AddField(
            model_name='convocationuser',
            name='convocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convocation_users', to='administration.convocationpage', verbose_name='Convocation'),
        ),
        migrations.AddField(
            model_name='convocationuser',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convocation_user_parents', to='wagtailcore.page', verbose_name='Parent Page'),
        ),
        migrations.AddField(
            model_name='convocationuser',
            name='substitute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convocation_user_substitutes', to=settings.AUTH_USER_MODEL, verbose_name='Substitute'),
        ),
        migrations.AddField(
            model_name='convocationuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='compterendupage',
            name='replaced_users',
            field=models.ManyToManyField(blank=True, related_name='replaced_cr', to='administration.convocationuser', verbose_name='Excusés et remplacés'),
        ),
        migrations.AddField(
            model_name='compterendupage',
            name='unreplaced_users',
            field=models.ManyToManyField(blank=True, related_name='unreplaced_cr', to='administration.convocationuser', verbose_name='Excusés non remplacés'),
        ),
        migrations.AlterUniqueTogether(
            name='convocationuser',
            unique_together={('convocation', 'user')},
        ),
    ]
