# Generated by Django 5.0 on 2024-03-27 16:09

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_convocationpage_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compterendupiecejointe',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='compte_rendu_documents', to='administration.compterendupage'),
        ),
    ]
