# Generated by Django 5.0.4 on 2024-04-17 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_administrationformpage_administrationpiecejointe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrationindexpage',
            options={'verbose_name': "Page d'ndex de l'administration"},
        ),
    ]
