# Generated by Django 5.0.4 on 2024-04-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_convocationpiecejointe_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='compterendupiecejointe',
            name='version',
            field=models.CharField(choices=[('numeric', 'Numeric version'), ('attachments', 'Attachments')], default='numeric', help_text='Choose if this is supposed to be a numeric version of the form or an attachment.', max_length=15, verbose_name='Type'),
        ),
    ]
