# Generated by Django 5.0 on 2024-05-02 00:53

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_compterendupiecejointe_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='compterendupage',
            name='technicians',
            field=wagtail.fields.StreamField([('technician', wagtail.blocks.CharBlock(form_classname='technician', icon='user', label='Technician'))], blank=True, help_text='First name LAST NAME and object if necessary.', null=True, verbose_name='Technicians'),
        ),
    ]
