# Generated by Django 5.0 on 2024-03-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='commission',
        ),
        migrations.RemoveField(
            model_name='user',
            name='function_commission',
        ),
        migrations.AddField(
            model_name='user',
            name='commissions',
            field=models.ManyToManyField(blank=True, to='administration.commissionpage', verbose_name='commissions'),
        ),
        migrations.AddField(
            model_name='user',
            name='functions_commissions',
            field=models.JSONField(blank=True, default=list, verbose_name='Functions in Commissions'),
        ),
    ]
